// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxjO8qixmP0FwY1HmQz6ZjSodvDqNPu3E',
    appId: '1:846106559591:android:c290af779d60c8a44f80c2',
    messagingSenderId: '846106559591',
    projectId: 'wildwherev2',
    storageBucket: 'wildwherev2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTUQ9breCNRJJaUKrI2T2YEb_1qCxYRJ4',
    appId: '1:846106559591:ios:e513f31a99be0da54f80c2',
    messagingSenderId: '846106559591',
    projectId: 'wildwherev2',
    storageBucket: 'wildwherev2.appspot.com',
    androidClientId: '846106559591-07injo27jk3hq946ps6efgn7ou59b2pp.apps.googleusercontent.com',
    iosClientId: '846106559591-c2l9dcbp4hk38s2ejne016emfpin63ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.wildwhere',
  );
}
